name: Tag and Release

on:
  push:
    branches:
      - master

jobs:
  tag-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch tags
        run: git fetch --tags

      - name: Get latest tag
        id: get-latest-tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "")
          if [ -z "$latest_tag" ]; then
            echo "latest_tag=v0.0.0" >> $GITHUB_ENV
          else
            echo "latest_tag=$latest_tag" >> $GITHUB_ENV
          fi

      - name: Calculate new tag
        id: calculate-new-tag
        run: |
          latest_tag=${{ env.latest_tag }}
          if [ "$latest_tag" == "v0.0.0" ]; then
            new_tag="v0.0.1"
          else
            IFS='.' read -r -a parts <<< "${latest_tag:1}"
            major=${parts[0]}
            minor=${parts[1]}
            patch=${parts[2]}

            if [ $patch -eq 9 ]; then
              patch=0
              minor=$((minor + 1))
            else
              patch=$((patch + 1))
            fi

            new_tag="v${major}.${minor}.${patch}"
          fi
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Create new tag
        run: |
          new_tag=${{ env.new_tag }}
          git tag $new_tag
          git push origin $new_tag

      - name: Generate Release Notes
        id: generate-release-notes
        run: |
          response=$(curl -s -L \
                            -X POST \
                            -H "Accept: application/vnd.github+json" \
                            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                            -H "X-GitHub-Api-Version: 2022-11-28" \
                            https://api.github.com/repos/${{ github.repository }}/releases/generate-notes \
                            -d '{"tag_name":"${{ env.new_tag }}","target_commitish":"master","previous_tag_name":"${{ env.latest_tag }}"}')
          echo "::set-output name=release_notes::${response//'%'/'%25'}"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.new_tag }}
          release_name: ${{ env.new_tag }}
          body: |-
            ${{ steps.generate-release-notes.outputs.release_notes }}
          draft: false
          prerelease: false
